const details = {
  bodyType: {
    Sedan: false,
    SUV: false,
    Truck: false,
    Coupe: false,
    Convertible: false,
    Hatchback: false,
    Van: false,
    Wagon: false,
  },
  fuelType: {
    Gasoline: false,
    Diesel: false,
    Electric: false,
    Hybrid: false,
    "Plug-in Hybrid": false,
  },
  transmission: {
    Automatic: false,
    Manual: false,
    CVT: false,
  },
  driveTrain: {
    AWD: false,
    FWD: false,
    RWD: false,
    "4WD": false,
  },
  condition: {
    New: false,
    Used: false,
    "Certified Pre-Owned": false,
    Salvage: false,
  },
  auctionStatus: {
    Active: false,
    "Ending Soon": false,
    "No Reserve": false,
    "Reserve Met": false,
    "Reserve Not Met": false,
  },
  sellerType: {
    Dealer: false,
    "Private Seller": false,
    Manufacturer: false,
  },
  locations: {
    "New York, NY": true,
    "Los Angeles, CA": false,
    "Chicago, IL": false,
    "Houston, TX": false,
    "Phoenix, AZ": false,
    "Miami, FL": false,
    "Seattle, WA": false,
    "Boston, MA": false,
    "Denver, CO": false,
    "Atlanta, GA": false,
  },
  makes: {
    Ford: false,
    Toyota: false,
    Honda: false,
    Hyundai: false,
    Suzuki: false,
    BMW: false,
    "Mercedes-Benz": false,
    Audi: false,
    Tesla: false,
    Porsche: false,
  },
  registeredIn: {
    California: false,
    Texas: false,
    "New York": false,
    Florida: false,
    Illinois: false,
  },
};

export default details;
